# Model arguments
model_name_or_path: 
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
data_path: 
dataset_splits:
- train
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: True
beta: 0.05
do_eval: False
#evaluation_strategy: 'no'
#eval_steps: 0
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: step-dpo
learning_rate: 1.0e-6
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 8192
max_prompt_length: 4096
num_train_epochs: 2
optim: adamw_torch
output_dir: data/step-dpo
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
report_to:
- tensorboard
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
